### ISSUE TITLE
Can we see screenshots in the readme?

### ISSUE THREAD

**Issue by spikespaz** [DeflatedPickle/pkinter#13]
Title. I want to know what this looks like before I use it.

**Comment by DeflatedPickle** [comment]
Apologies for such a late reply, I forgot I never replied to this. The README used to have a GIF for each widget, but it got quite long and they were tedious to record.

I could just take a screenshot of the test GUI and call it a day there, but if you have any ideas on showing off each widget without making as much of a mess as I did, and you're still interested in the project, then please feel free to reply to this. If not, I'll be closing the issue whenever, probably at the beginning of next year.

**Comment by spikespaz** [comment]
It's a little bit dead. I switched to compiled languages for the most part.

**Comment by DeflatedPickle** [comment]
Alright, good luck with that! I've done the same, mostly. Even thinking about rewriting this in something like D and writing wrappers!
